<?php

namespace AppBundle\Repository;

/**
 * SpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $user_id
     * @return double
     */
    public function getSpots($user_id = null)
    {
        if(isset($user_id)) {
          $query = $this->createQueryBuilder('spot')
                        ->where('spot.user = :user_id')
                        ->setParameter('user_id', $user_id);
        } else {
          $query = $this->createQueryBuilder('spot');
        }

        return $query;
    }
}
